treewide: Harden against integer overflows in DIV_ROUND_UP()
Herbert Xu notes that DIV_ROUND_UP() may overflow unnecessarily and
instead suggests (for a division by 8):

  X / 8 + !!(X & 7)

Based on this formula, a generic DIV_ROUND_UP_POW2() macro has just been
introduced.  Use it in DIV_ROUND_UP() for any constant divisor which is
a power of 2.

Convert all occurrences of DIV_ROUND_UP_POW2() in the crypto subsystem
to DIV_ROUND_UP(), which will internally expand to DIV_ROUND_UP_POW2().

Unfortunately wherever DIV_ROUND_UP() is used to size an array, gcc will
now raise errors such as:

  include/linux/tcp.h:91:17: error: variably modified 'val' at file scope
  __le64  val[DIV_ROUND_UP(TCP_FASTOPEN_COOKIE_MAX, sizeof(u64))];

It seems gcc does not lower the more complex DIV_ROUND_UP() macro before
determining whether an array is variably sized.  Work around by using
__KERNEL_DIV_ROUND_UP() in lieu of DIV_ROUND_UP() wherever it's used
to size arrays.  Same for initializers of static variables.

Link: https://lore.kernel.org/r/Z3iElsILmoSu6FuC@gondor.apana.org.au/
Signed-off-by: Lukas Wunner <lukas@wunner.de>